#!/bin/bash

ROOT="$HOME/GLASS/glass"
#ROOT="$HOME/GLASS/glass-DEV"
#ROOT="$HOME/GAGL/glass"

PYTHON="python"
PLATDIR=`$PYTHON -c "import distutils.util, sys; print 'lib.%s-%s' % (distutils.util.get_platform(), sys.version[0:3])"`
GLASS="$PYTHON $ROOT/build/$PLATDIR/glass/glass.py"
export   LD_LIBRARY_PATH=$ROOT/glass/solvers/rwalk/lp_solve_5.5/extra/Python/build/$PLATDIR:$LD_LIBRARY_PATH
export   LD_LIBRARY_PATH=$ROOT/glass/solvers/rwalk/glpk_build/lib:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$ROOT/glass/solvers/rwalk/lp_solve_5.5/extra/Python/build/$PLATDIR:$DYLD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$ROOT/glass/solvers/rwalk/lp_solve_5.5/lpsolve55:$DYLD_LIBRARY_PATH
export PYTHONPATH=$HOME/pynbody/build/$PLATDIR:$PYTHONPATH
export PYTHONPATH=$HOME/pynbody/pynbody/build/$PLATDIR:$PYTHONPATH
export PYTHONPATH=$ROOT/glass/solvers/rwalk/lp_solve_5.5/extra/Python/build/$PLATDIR:$PYTHONPATH
export PYTHONPATH=$ROOT/glass/solvers/rwalk/python-glpk-0.4.43/src/build/$PLATDIR/glpk/:$PYTHONPATH

$GLASS $*

